-- [ JOIN 문제 ] --
-- 1. 부서가 인사관리부인 사원의 사번, 이름, 부서명, 보너스 조회
--== 오라클 전용 구문 ==--
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, BONUS FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID AND DEPT_TITLE = '인사관리부';

--== ANSI 구문 ==--
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, BONUS FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID WHERE DEPT_TITLE = '인사관리부';


-- 2. DEPARTMENT와 LOCATION을 참고하여 전체 부서의 부서코드, 부서명, 지역코드, 지역명 조회
--== 오라클 전용 구문 ==--
SELECT DEPT_ID, DEPT_TITLE, LOCAL_CODE, LOCAL_NAME FROM DEPARTMENT D, LOCATION L
WHERE D.LOCATION_ID = L.LOCAL_CODE;

--== ANSI 구문 ==--
SELECT DEPT_ID, DEPT_TITLE, LOCAL_CODE, LOCAL_NAME FROM DEPARTMENT D
JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE;


-- 3. 보너스를 받는 사원들의 사번, 사원명, 보너스, 부서명 조회
--== 오라클 전용 구문 ==--
SELECT EMP_ID, EMP_NAME, BONUS, DEPT_TITLE FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID AND BONUS IS NOT NULL;

--== ANSI 구문 ==--
SELECT EMP_ID, EMP_NAME, BONUS, DEPT_TITLE FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID WHERE BONUS IS NOT NULL;


-- 4. 부서가 총무부가 아닌 사원들의 사원명, 급여, 부서명 조회
--== 오라클 전용 구문 ==--
SELECT EMP_NAME, SALARY, DEPT_TITLE FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID AND DEPT_TITLE <> '총무부';

--== ANSI 구문 ==--
SELECT EMP_NAME, SALARY, DEPT_TITLE FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID WHERE DEPT_TITLE <> '총무부';


-- 5. 사번, 사원명, 부서명, 지역명, 국가명 조회(EMPLOYEE, DEPARTMENT, LOCATION, NATIONAL 조인)
--== 오라클 전용 구문 ==--
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME FROM EMPLOYEE E, DEPARTMENT D, LOCATION L, NATIONAL N
WHERE E.DEPT_CODE = D.DEPT_ID AND D.LOCATION_ID = L.LOCAL_CODE AND L.NATIONAL_CODE = N.NATIONAL_CODE;

--== ANSI 구문 ==--
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
JOIN NATIONAL USING (NATIONAL_CODE);


-- 6. 사번, 사원명, 부서명, 직급명, 지역명, 국가명, 급여등급 조회(모든 테이블 다 조인)
--== 오라클 전용 구문 ==--
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, LOCAL_NAME, NATIONAL_NAME, SAL_LEVEL
FROM EMPLOYEE E, DEPARTMENT D,  JOB J, LOCATION L, NATIONAL N, SAL_GRADE S
WHERE E.DEPT_CODE = D.DEPT_ID AND E.JOB_CODE = J.JOB_CODE AND D.LOCATION_ID = L.LOCAL_CODE
AND L.NATIONAL_CODE = N.NATIONAL_CODE AND SALARY BETWEEN MIN_SAL AND MAX_SAL;

--== ANSI 구문 ==--
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, LOCAL_NAME, NATIONAL_NAME, SAL_LEVEL FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
JOIN NATIONAL USING (NATIONAL_CODE)
JOIN SAL_GRADE ON (SALARY BETWEEN MIN_SAL AND MAX_SAL);